name: ruhe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  provider: ^6.1.2
  google_generative_ai: ^0.4.6
  http: ^1.3.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo_ruhe.svg
    - lib/assets/logo_purple.svg  

  fonts:
    - family: Sansation
      fonts:
        - asset: lib/assets/fonts/Sansation-Regular.ttf
